apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  selector:
    app: telegraf
  ports:
  - protocol: UDP
    port: 8125
    targetPort: 8125
  type: ClusterIP
