apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  ports:
  - name: ftps21
    port: 21
    protocol: TCP
    targetPort: 20
  selector:
    app: ftps
  type: LoadBalancer
