apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  ports:
  - name: ftps21
    port: 21
    protocol: TCP
    targetPort: 21
  - name: ftps30000
    port: 30000
    protocol: TCP
    targetPort: 30000
  - name: ftps30001
    port: 30001
    protocol: TCP
    targetPort: 30001
  - name: ftps30002
    port: 30002
    protocol: TCP
    targetPort: 30002
  selector:
    app: ftps
  type: LoadBalancer
