apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
    - name: php-port
      protocol: TCP
      port: 5000
      targetPort: 80
  type: LoadBalancer
